### PR TITLE
finish renaming sink to view

### PR DESCRIPTION
**Pull request by demmer**
Another pass through the compiler to replace instances of 'sink' with 'view' as appropriate.
Details in the specific commits.

Closes #24 

Note that outrigger will need to be updated once this merges.

### CODE REVIEW

**Comment by demmer** [comment]
@dmajda @bkutil @mstemm

**Comment by mstemm** [comment]
These changes look fine but I think @dmajda/@bkutil should also take a look.

My grep for sink is still finding lots of instances, but it looks like those are for the base class and as a result are appropriate.

**Comment by demmer** [comment]
Yep. As far as I can tell all remaining instances of sink are proper. 

-m

**Comment by dmajda** [comment]
Grepping revealed there is a `sinks` variable [in `build.js`](https://github.com/juttle/juttle/blob/afd5031dee1a3246258f51adc460d4e66a5a3fd1/lib/compiler/build.js#L77) which looks unused. I’m fine with both removing it now or later (together with flattening the object returned from the builder function so that there is no `graph` property).

**Comment by dmajda** [comment]
I think [this comment](https://github.com/juttle/juttle/blob/afd5031dee1a3246258f51adc460d4e66a5a3fd1/lib/compiler/graph-compiler.js#L463) should be updated too.

**Comment by dmajda** [comment]
Hmm, [this comment](https://github.com/juttle/juttle/blob/afd5031dee1a3246258f51adc460d4e66a5a3fd1/lib/parser/parser.pegjs#L1182) is no longer true (will fix separately).

**Comment by dmajda** [comment]
Other than this, I think all remaining uses of “sink” are legit. There is a couple of pieces of Juttle code like `... | view sink1` in the tests, which I think could be changed too, but not necessarily. Similarly with few “sink” instances [here](https://github.com/juttle/juttle/blob/afd5031dee1a3246258f51adc460d4e66a5a3fd1/docs/doc_templates/usage_snippets.md).

+1

**Comment by dmajda** [comment]
OK, I fixed small semi-related issues separately.

**Pull request merged**
