### PR TITLE
Remove pubsub

### PR DESCRIPTION
**Pull request by bkutil**
As the `TestView` was the last view depending on the pub sub system, modify it so it uses `program.events`. Then gradually remove dependencies on the `publish` and `subscribe` procs from the inheritance chains and from the code.

### CODE REVIEW

**Comment by bkutil** [comment]
cc: @dmajda @demmer

**Comment by dmajda** [comment]
+1

@bkutil The [CI failure](https://travis-ci.org/juttle/juttle/builds/105644840) seems to be because of decreased coverage, which seems odd given this PR mostly removes code. Please investigate and adjust the numbers if necessary before merging.

**Comment by bkutil** [comment]
Rebased

**Comment by bkutil** [comment]
I'll move the channel allocation to a method on program in a separate PR.

**Pull request merged**
