### PR TITLE
parser: Avoid module recursion in parser.parse{Value,Filter}

### LINKED ISSUE #163: Don’t do module-recursive parsing in `parser.parse{Value,Filter}`
Currently we do module-recursive parsing in `parser.parse{Value,Filter}` which means the results are decorated with the `modules` property:

```
$ node
> var parser = require('./lib/parser');
undefined
> parser.parseValue('5');
{ type: 'NumericLiteral',
  location: 
   { filename: 'main',
     start: { offset: 0, line: 1, column: 1 },
     end: { offset: 1, line: 1, column: 2 } },
  value: 5,
  modules: [] }
> parser.parseFilter('a < 5');
{ type: 'FilterLiteral',
  location: 
   { filename: 'main',
     start: { offset: 0, line: 1, column: 1 },
     end: { offset: 5, line: 1, column: 6 } },
  ast: 
   { type: 'ExpressionFilterTerm',
     location: { filename: 'main', start: [Object], end: [Object] },
     expression: 
      { type: 'BinaryExpression',
        location: [Object],
        operator: '<',
        left: [Object],
        right: [Object] } },
  text: 'a < 5',
  modules: [] }
```

### PR DESCRIPTION
**Pull request by dmajda**
Fixes #163.

### CODE REVIEW

**Comment by dmajda** [comment]
@bkutil

**Comment by dmajda** [comment]
The [test failure](https://travis-ci.org/juttle/juttle/jobs/102364387) is not relevant to this change, filed #181, re-running.

**Comment by bkutil** [comment]
The commit message could be a bit more verbose (what was the problem and why this fixes it), but +1 :)

**Comment by dmajda** [comment]
Not in a verbose mood today :-)

More seriously, this fixes a problem of marginal importance and impact, so I figured an issue reference is good enough.

**Pull request merged**
