### PR TITLE
shell adapter

### PR DESCRIPTION
**Pull request by rlgomes**
NOT READY FOR MERGE

@juttle/developers opinions requested...

This is merely a prototype to see what others think but I ran into the situation where I wanted to run an external program and then use its output to create a data stream and also had the situation where I wanted that run to be repeated as to create a pseudo live stream with a command line tool. 

The one situation I had was to use my battery charge/discharge information to plot how my battery life was doing over time but then I also found a few more useful situations such as being able to monitor the disk space using `df` of a local system:

```
> ./bin/juttle -e "read shell -command 'df' -format 'columns' | put time = Date.time()"            
┌────────────────────────────────────┬──────────────┬──────────────┬─────────────────────────────────┬─────────────────────┬──────────┬──────────┬──────────────┐
│ time                               │ 1K-blocks    │ Available    │ Filesystem                      │ Mounted             │ on       │ Use%     │ Used         │
├────────────────────────────────────┼──────────────┼──────────────┼─────────────────────────────────┼─────────────────────┼──────────┼──────────┼──────────────┤
│ 2016-03-16T21:13:38.649Z           │ 8047872      │ 8047868      │ udev                            │ /dev                │ null     │ 1%       │ 4            │
├────────────────────────────────────┼──────────────┼──────────────┼─────────────────────────────────┼─────────────────────┼──────────┼──────────┼──────────────┤
│ 2016-03-16T21:13:38.649Z           │ 1612688      │ 1611284      │ tmpfs                           │ /run                │ null     │ 1%       │ 1404         │
├────────────────────────────────────┼──────────────┼──────────────┼─────────────────────────────────┼─────────────────────┼──────────┼──────────┼──────────────┤
│ 2016-03-16T21:13:38.649Z           │ 23899880     │ 15401264     │ /dev/sda2                       │ /                   │ null     │ 33%      │ 7261532      │
├────────────────────────────────────┼──────────────┼──────────────┼─────────────────────────────────┼─────────────────────┼──────────┼──────────┼──────────────┤
│ 2016-03-16T21:13:38.649Z           │ 4            │ 4            │ none                            │ /sys/fs/cgroup      │ null     │ 0%       │ 0            │
├────────────────────────────────────┼──────────────┼──────────────┼─────────────────────────────────┼─────────────────────┼──────────┼──────────┼──────────────┤
│ 2016-03-16T21:13:38.649Z           │ 5120         │ 5120         │ none                            │ /run/lock           │ null     │ 0%       │ 0            │
├────────────────────────────────────┼──────────────┼──────────────┼─────────────────────────────────┼─────────────────────┼──────────┼──────────┼──────────────┤
│ 2016-03-16T21:13:38.649Z           │ 8063432      │ 7957560      │ none                            │ /run/shm            │ null     │ 2%       │ 105872       │
├────────────────────────────────────┼──────────────┼──────────────┼─────────────────────────────────┼─────────────────────┼──────────┼──────────┼──────────────┤
│ 2016-03-16T21:13:38.649Z           │ 102400       │ 102372       │ none                            │ /run/user           │ null     │ 1%       │ 28           │
├────────────────────────────────────┼──────────────┼──────────────┼─────────────────────────────────┼─────────────────────┼──────────┼──────────┼──────────────┤
│ 2016-03-16T21:13:38.649Z           │ 192171612    │ 70616748     │ /dev/sda5                       │ /home               │ null     │ 62%      │ 111770032    │
├────────────────────────────────────┼──────────────┼──────────────┼─────────────────────────────────┼─────────────────────┼──────────┼──────────┼──────────────┤
│ 2016-03-16T21:13:38.650Z           │ 192171612    │ 70616748     │ /home/rlgomes/.Private          │ /home/rlgomes       │ null     │ 62%      │ 111770032    │
└────────────────────────────────────┴──────────────┴──────────────┴─────────────────────────────────┴─────────────────────┴──────────┴──────────┴──────────────┘
```
and then if you wanted to keep rerunning at the `-every` interval simply add the `-to :end:` and the program is re-executed every 5s generating new data from the `df` command.

I only implemented the `read` at this point and the write is just copy/pasta but wanted to get feedback on the name `shell` adapter vs any other suggestion and also if we should have differently named arguments ? For example I'm more included to have the user specify a single command line `-command 'df -h /special/mount/point'` than the current approach of `-command 'df' -args ['-h','/special/mount/point']` but only because its easier to write while the `-command`, and `-args` options give more flexibility.

The really nice thing is how the various parsers automatically give us the ability to nicely parse things as I used above the `columns` parser to transform the output of df directly into a point stream.

### CODE REVIEW

**Comment by dmehra** [comment]
Now that I see how it works, why `read shell` and not `read stdio` (if it supported columns)?
```
df | juttle -e "read stdio -format 'columns' | put time = Date.time()"
```

**Comment by rlgomes** [comment]
@dmehra `read stdio` will not rerun the df command for you, another interesting one is that eventually when we have first class flowgraphs we'd be able to also drive part of the command through values calculated in the stream itself.

**Comment by rlgomes** [comment]
@dmehra there's also the write part of this which would allow to push data (csv/json) to a command that would then do something that isn't available through an API or any other existing adapter. This may very well be just a temporary thing in most cases but I can see a lot of legacy systems that don't have APIs available and instead have some proprietary libraries that communicate over something other than HTTP and a command line tool is the only way to trigger certain actions.

**Comment by dmehra** [comment]
Show me how `read shell` would re-run the command for me? Do you mean `read shell -every :1m: -command 'df'` would actually run df every minute?

**Comment by rlgomes** [comment]
@dmehra run `-to :end:` 

```
rlgomes@x230> ./bin/juttle -e "read shell -to :end: -command 'df' -format 'columns' | put time = Date.time() | view text"
[
{"Filesystem":"udev","1K-blocks":"8047872","Used":"4","Available":"8047868","Use%":"1%","Mounted":"/dev","on":null,"time":"2016-03-16T22:10:09.295Z"},
{"Filesystem":"tmpfs","1K-blocks":"1612688","Used":"1404","Available":"1611284","Use%":"1%","Mounted":"/run","on":null,"time":"2016-03-16T22:10:09.295Z"},
{"Filesystem":"/dev/sda2","1K-blocks":"23899880","Used":"7260896","Available":"15401900","Use%":"33%","Mounted":"/","on":null,"time":"2016-03-16T22:10:09.295Z"},
{"Filesystem":"none","1K-blocks":"4","Used":"0","Available":"4","Use%":"0%","Mounted":"/sys/fs/cgroup","on":null,"time":"2016-03-16T22:10:09.295Z"},
{"Filesystem":"none","1K-blocks":"5120","Used":"0","Available":"5120","Use%":"0%","Mounted":"/run/lock","on":null,"time":"2016-03-16T22:10:09.295Z"},
{"Filesystem":"none","1K-blocks":"8063432","Used":"110584","Available":"7952848","Use%":"2%","Mounted":"/run/shm","on":null,"time":"2016-03-16T22:10:09.295Z"},
{"Filesystem":"none","1K-blocks":"102400","Used":"28","Available":"102372","Use%":"1%","Mounted":"/run/user","on":null,"time":"2016-03-16T22:10:09.295Z"},
{"Filesystem":"/dev/sda5","1K-blocks":"192171612","Used":"111770676","Available":"70616104","Use%":"62%","Mounted":"/home","on":null,"time":"2016-03-16T22:10:09.295Z"},
{"Filesystem":"/home/rlgomes/.Private","1K-blocks":"192171612","Used":"111770676","Available":"70616104","Use%":"62%","Mounted":"/home/rlgomes","on":null,"time":"2016-03-16T22:10:09.295Z"},
{"Filesystem":"udev","1K-blocks":"8047872","Used":"4","Available":"8047868","Use%":"1%","Mounted":"/dev","on":null,"time":"2016-03-16T22:10:14.181Z"},
{"Filesystem":"tmpfs","1K-blocks":"1612688","Used":"1404","Available":"1611284","Use%":"1%","Mounted":"/run","on":null,"time":"2016-03-16T22:10:14.181Z"},
{"Filesystem":"/dev/sda2","1K-blocks":"23899880","Used":"7260900","Available":"15401896","Use%":"33%","Mounted":"/","on":null,"time":"2016-03-16T22:10:14.181Z"},
{"Filesystem":"none","1K-blocks":"4","Used":"0","Available":"4","Use%":"0%","Mounted":"/sys/fs/cgroup","on":null,"time":"2016-03-16T22:10:14.181Z"},
{"Filesystem":"none","1K-blocks":"5120","Used":"0","Available":"5120","Use%":"0%","Mounted":"/run/lock","on":null,"time":"2016-03-16T22:10:14.181Z"},
{"Filesystem":"none","1K-blocks":"8063432","Used":"109880","Available":"7953552","Use%":"2%","Mounted":"/run/shm","on":null,"time":"2016-03-16T22:10:14.181Z"},
{"Filesystem":"none","1K-blocks":"102400","Used":"28","Available":"102372","Use%":"1%","Mounted":"/run/user","on":null,"time":"2016-03-16T22:10:14.181Z"},
{"Filesystem":"/dev/sda5","1K-blocks":"192171612","Used":"111770656","Available":"70616124","Use%":"62%","Mounted":"/home","on":null,"time":"2016-03-16T22:10:14.181Z"},
{"Filesystem":"/home/rlgomes/.Private","1K-blocks":"192171612","Used":"111770656","Available":"70616124","Use%":"62%","Mounted":"/home/rlgomes","on":null,"time":"2016-03-16T22:10:14.181Z"}^C
...
```

**Comment by mstemm** [comment]
You could obtain the same scheduling outside of juttle and use the stdio adapter, though:

```
while true; do df; sleep 5; done | bin/juttle -e 'read stdio -format 'columns' | put time = Date.time() | view text'
```

I'm not sure it's worth adding a whole new adapter just to get the ability to periodically run a command.

**Comment by rlgomes** [comment]
@mstemm that wouldn't work from within the `juttle-engine` nor is there anyway to trigger an external command at the end of a juttle flowgraph at that point either. Closing this PR till a customer asks for such a feature.

**Comment by rlgomes** [comment]
@mstemm your example doesn't work due to a bug in the stdio adapter where we didn't copy the logic to use an Iterator like we did in the file adapter and we're basically buffering everything before pushing it down the pipeline. I'll open an issue and fix this.

**Pull request closed without merging**
