### PR TITLE
Remove unused proc initializer params

### LINKED ISSUE #132: Get rid of `pname` and `juttle` arguments of `Juttle.proc.base#initialize`
While going through the gmail adapter docs, I noticed that I didn't know what the ``pname`` and ``juttle`` arguments to
```
initialize: function(options, params, pname, location, program, juttle) {...}
```
are for.

Can you provide a description or if they are not needed remove them? That makes the API for new adapter writers a bit cleaner.

### PR DESCRIPTION
**Pull request by dmajda**
Remove `juttle` and `pname` parameters from proc initializers.

Fixes #132.

### CODE REVIEW

**Comment by dmajda** [comment]
@mstemm 

@demmer Is `Program#get_stats` removal OK with you?

**Comment by mstemm** [comment]
The changes look good to me. I'll let @demmer also chime in.

**Comment by dmajda** [comment]
The [test failure](https://travis-ci.org/juttle/juttle/jobs/101880046) is unrelated to the change and caused by #152.

**Comment by demmer** [comment]
I'm good with removing `Program#get_stats` and the rest of the code looks good to me as well.

**Comment by dmajda** [comment]
Rebased to resolve a conflict, will merge on green.

**Pull request merged**
