### PR TITLE
add location informationt to runaway errors

### LINKED ISSUE #572: Runaway program detector errors have no location information
Example:

```
$ bin/juttle -e 'read file -file "xxx" -from :beginning: -to :end: | tail 1'
Error: Not starting program as it would run forever with no output. Add a -to option to read?
```

### PR DESCRIPTION
**Pull request by rlgomes**
fixes #572

pretty straightforward change to make sure we pass location information
along with the error when detecting a runaway program

### CODE REVIEW

**Comment by rlgomes** [comment]
@dmajda @bkutil

**Comment by rlgomes** [comment]
Oh example output:

```
rlgomes@x230> bin/juttle -e 'read file -file "xxx" -from :beginning: -to :end: | tail 1'
<input>:1:53: 
   1:read file -file "xxx" -from :beginning: -to :end: | tail 1
                                                         ^^^^^^
Error: Not starting program as it would run forever with no output. Add a -to option to read? (RUNAWAY-PROGRAM)
```

**Comment by bkutil** [comment]
Shouldn't the location point to `readNode` instead of `nextNode`? I.e. highlight the `read` not `tail` in the example above?

**Comment by rlgomes** [comment]
@bkutil yo'ure right since its indicating to add the `-to` message that makes more sense... let me look at each one and make sure the message matches the node that is at fault. Good catch!

**Comment by rlgomes** [comment]
And I'll add tests to verify the location stays correct with any future changes in this area.

**Comment by rlgomes** [comment]
@bkutil 
```
rlgomes@x230> bin/juttle -e 'read file -file "xxx" -from :beginning: -to :end: | tail 1'
<input>:1:1: 
   1:read file -file "xxx" -from :beginning: -to :end: | tail 1
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Not starting program as it would run forever with no output. Add a -to option to read? (RUNAWAY-PROGRAM)
```

**Comment by bkutil** [comment]
Looks good! :) +1

**Pull request merged**
