### PR TITLE
Add tests for nested points in join proc

### PR DESCRIPTION
**Pull request by bkutil**
Join proc works without modifications for nested points (as it relies on groups, which have been already updated). Just add tests (tm).

### CODE REVIEW

**Comment by bkutil** [comment]
cc: @dmajda

**Comment by bkutil** [comment]
refs: #55

**Comment by dmajda** [comment]
Is there a specific reason why these 3 tests?

**Comment by bkutil** [comment]
Yes - I noticed three major classes of tests for joins and added one of the tests for each of those:

1. a simple case (join of 3 streams into 1)
2. an outer join
3. a join by

I'll fix the commit message to state this. Do you think some other class of tests is missing?

**Comment by dmajda** [comment]
> I'll fix the commit message to state this. Do you think some other class of tests is missing?

No. There are many other kinds of joins, but I don’t think they treat points differently, so the coverage you added is sufficient.

(I was thinking that maybe you modeled this after the `join` code, trying to cover different code paths.)

+1

**Comment by bkutil** [comment]
Yeah, it looks like I missed `nearest`, `zip` and `once`...

**Pull request merged**
