### PR TITLE
Support indexed assignment in assignment expressions

### PR DESCRIPTION
**Pull request by dmajda**
This change brings assignment expressions closer to assignment statements which already support indexed assignment.

Part of work on #426.

### CODE REVIEW

**Comment by dmajda** [comment]
@bkutil

**Comment by bkutil** [comment]
+1.

Maybe it'd be better to expand the GH issue reference in the test to include

a) a full link
b) name and/or a brief summary of the referenced feature.

The number alone doesn't provide the required context.

**Comment by dmajda** [comment]
@bkutil A reference to an issue number seems good enough to me but I added some more context. Better?

**Comment by bkutil** [comment]
Ok.

**Pull request merged**
