### PR TITLE
Make reduce -every emit marks at the end of epoch

### PR DESCRIPTION
**Pull request by bkutil**
`reduce -every` emits marks at the end of each epoch. This also requires changes for sort and tests that depend on the old behavior.

### CODE REVIEW

**Comment by bkutil** [comment]
The only tests that fail now are out-of-order tests. The issue is that marks after reduce now move the 'ooo-treshold' in `oops_fanin` forward, and so e.g. where a sequence of times `:1: | :0: | :1: | :0:` (`|` is a reduce boundary) would previously result in `:1: :1:`, with marks carrying the timestamp of the boundary, everything after the first point is dropped as ooo.

**Comment by bkutil** [comment]
cc: @dmajda

**Comment by dmajda** [comment]
+1

**Comment by bkutil** [comment]
Updated to use `super` instead of `prototype.x.call` and updated commit messages. Will merge on green.

**Comment by bkutil** [comment]
Fixes #52

**Pull request merged**
