### PR TITLE
Deactivate program after running it

### PR DESCRIPTION
**Pull request by bkutil**
Procs and scheduler depend on the program deactivation after juttle runs
and not doing that can lead to leaking timers.

Fix calls to `run_juttle` or `program.activate` that were missing a
corresponding `program.deactivate` call.

### CODE REVIEW

**Comment by bkutil** [comment]
cc: @dmajda

**Comment by dmajda** [comment]
Would it be possible to move the deactivation logic from `check_juttle` to `run_juttle` so that explicit deactivation is avoided? Or are there any cases where tests depend on programs *not* being deactivated?

**Comment by bkutil** [comment]
Yeah, that would actually be a better approach. I'll patch `run_juttle` itself.

**Comment by bkutil** [comment]
@dmajda done - it seems juttle spec was generating deactivation code. Is it still necessary? IMHO it is not needed anymore...

**Comment by dmajda** [comment]
+1, but at some point we should move `deactivateAfter` to options.

**Comment by bkutil** [comment]
Updated the `deactivateAfter` to be an option instead of a parameter.

**Pull request merged**
