### PR TITLE
CSV stdio serializer supports arrays/objects

### PR DESCRIPTION
**Pull request by bkutil**
Serialize array/object values using JSON, to keep point structure flat
and processable by CSV writer.

### CODE REVIEW

**Comment by bkutil** [comment]
cc: @dmajda

refs: #55

**Comment by rlgomes** [comment]
@bkutil looks good I do think at some point we need to come up with a nicer way of apply *P* functions to every point or *F* functions to every field in a point in a way that doesn't mean having to iterating through the same *N* points a bunch of times. This just occurred to me given how we're currently doing a few of these *N* loops for adding `timeField` and now applying this values thing to each field.

**Comment by rlgomes** [comment]
+1

**Comment by dmajda** [comment]
+1

**Pull request merged**
