### PR TITLE
JuttleMoment compare returns -1, 0, 1

### PR DESCRIPTION
**Pull request by bkutil**
To be consistent with `values.js` compare and simplify the
implementation a bit, make `compare` for JuttleMoments return -1, 0, 1
for smaller, equal, or greater values.

Update the helper functions (`lt` / `gt`...) to handle new return values.

### CODE REVIEW

**Comment by bkutil** [comment]
cc: @dmajda

**Comment by davidvgalbraith** [comment]
+1, this is long-needed functionality.

**Comment by dmajda** [comment]
I’d combine the first two commits as changing `compare` without changing its caller isn’t atomic.

**Comment by dmajda** [comment]
+1 with the comments addressed

**Comment by bkutil** [comment]
Thanks :) Squashed two non-atomic commits, removed the dead code. Will merge on green.

**Pull request merged**
