### PR TITLE
fix JavaScript capitalization

### PR DESCRIPTION
**Pull request by go-oleg**
Change from Javascript to JavaScript. As far as I can tell, this is _the_ accepted way to spell/capitalize it.

@mstemm @dmajda

### CODE REVIEW

**Comment by dmehra** [comment]
+1

**Comment by dmajda** [comment]
There is also a couple of places where JavaScript is spelled “javascript”, these should probably be changed too.

**Comment by go-oleg** [comment]
@dmajda, done.

**Comment by dmajda** [comment]
+1

**Pull request merged**
