### PR TITLE
Add nested expression tests for “.” and “[]” operators

### PR DESCRIPTION
**Pull request by dmajda**
Just to make sure this situation is covered.

Part of work on #419.

### CODE REVIEW

**Comment by dmajda** [comment]
@bkutil

**Comment by bkutil** [comment]
Cool! What happens if one of the fields in the nested chain doesn't exist?

**Comment by dmajda** [comment]
You’ll get `null` as a result and then a type error further in the chaing because `.` or `[]` on `null` is incorrect.

I added this case to the tests.

**Comment by bkutil** [comment]
+1

**Pull request merged**
