### PR TITLE
read.spec.js - fix http adapter tests requiring delayed deactivate

### PR DESCRIPTION
**Pull request by bkutil**

### CODE REVIEW

**Comment by bkutil** [comment]
cc: @rlgomes

**Comment by rlgomes** [comment]
Humm this doesn't seem right if the program doesn't finish on its own and needs to be deactivated after 250ms when it should simply stop and eof itself. Also the 250ms is just the right amount of time for the existing HTTP requests to finish up before the program is stopped which means if they take a bit longer these tests will fail since the deactivation would happen earlier than it should. So what is the adapter itself not doing to finish things up correctly aside from issuing the eof when it should ?

**Comment by bkutil** [comment]
I think the problem is that program finishes too early, i.e. without waiting for the adapter to return the results - which causes the tests to fail. (The other tests in http read used the delayed activation as well, maybe for the same reason?)

But I don't know how the correct logic should look like - I asked about it in #528.

**Comment by rlgomes** [comment]
@demmer @davidvgalbraith maybe you guys can shed some light on this, as the `deactivateAfter` feature was for live programs that wouldn't terminate and you wanted to run a juttle program for a period of time knowing that it would generate some data in that time frame that you could validate. Now `deactivateAfter` is being used on a program that isn't a long running program and it would be hard for anyone even writing tests to know if you should set the `deactivateAfter` or not ? Also this is going to generate a lot of flaky test behavior given the nature of guessing how much time should you wait to see data.

**Comment by demmer** [comment]
This proposal is misguided -- the underlying problem is that unless `deactivateAfter` is passed as an option, we shouldn't be calling deactivate until the program completes. See #532 for the proper fix.

**Pull request closed without merging**
