### PR TITLE
Address feedback on cli docs.

### PR DESCRIPTION
**Pull request by mstemm**
Add to mkdocs.yml, add link to adapters page from adapters section,
add link for gmail adapter on adapters page.

@dmehra can you double-check that I added the link to mkdocs.yml properly?

### CODE REVIEW

**Comment by dmehra** [comment]
Link is functionally correct, but might be better placed toward the end, above style guide. @demmer got preference?

**Comment by mstemm** [comment]
I'm not sure where in the README.md you mean by "toward the end, above style guide". Can you say the line number?

**Comment by dmehra** [comment]
mkdocs.yml:126 instead of 122, please. just above "juttle style guide".

**Comment by mstemm** [comment]
Oh ok, I thought you meant the README.md. Lemme fix.

**Comment by mstemm** [comment]
Also renaming GMail to Gmail, to be consistent with juttle-gmail-adapter.

**Comment by mstemm** [comment]
@dmehra is this ready to merge now?

**Comment by dmehra** [comment]
Sure is! Go ahead and I'll republish docs with this.

**Pull request merged**
