### PR TITLE
Add tests for non-scalar fields group by for put, head and tail

### PR DESCRIPTION
**Pull request by bkutil**
refs: https://github.com/juttle/juttle/issues/55

### CODE REVIEW

**Comment by bkutil** [comment]
cc: @dmehra @dmajda

**Comment by dmehra** [comment]
+1 assuming that objects with lists are covered elsewhere so it's sufficient to use a simple `"o": { "a": 1 }` here. What I mean is that other test generically covers handling of objects like `"o": { "a": 1, "b": 2 }` so we don't need to use them in each proc testcase.

**Comment by bkutil** [comment]
@dmehra - added tests that exercise grouping by object, array, object containing arrays and arrays containing objects...

**Comment by bkutil** [comment]
Merging based on +1 from @dmehra

**Pull request merged**
