### PR TITLE
source base class read logic

### PR DESCRIPTION
**Pull request by demmer**
NOT FOR MERGE

Initial cut at an implementation of the source base class support described in #168 for reading data from the subclass using a new `read(from, to, limit, state)` API function that is responsible for actually fetching or generating the data.

This should enable support for paging and pseudo-live queries in each of the adapters and is amenable to future integration with the flow-control scheduler described in #167. Also all the management of ticks is handled by the base class as opposed to having to be scattered through all the sources.

In this PR I also reimplemented `emit` as if it were an adapter using this contract. However given the unusual semantics that emit has for its behavior with -limit, -from, and -to options, this turned out to be a bit complicated in parts and seems like a step backwards in clarity from the older implementation.

I still haven't given up hope though -- maybe it makes sense to change some of the emit expectations to be closer to that of other sources... still TBD.

### CODE REVIEW

**Comment by demmer** [comment]
@davidvgalbraith @bkutil @dmajda @mstemm @VladVega Some initial feedback would be great -- I'd like to follow up with an implementation of one of the real adapters (influx probably) using this model to see that it actually works in practice with something real.

**Comment by dmajda** [comment]
On the high level I like what is in the `source` class (I’d have some small comments about naming and splitting things up a bit more but I’ll hold them at this phase).

Regarding state passing, I realized a cleaner way to implement this could be an iterator. In TypeScript-like syntax:

```typescript
class Iterator {
    // Here goes the iteration state, e.g. next offset in SQL adapters.
	
    getNext(): Promise<Point[]> | null {
        // ...
    }
}

class Adapter {
    read(from, to, n): Iterator {
        return new Iterator(...);	
    }
}
```

Inside `read` one would do something like:

```javascript
var iterator = adapter.read(...);

// This loop would really be async & promisified, use the scheduler, etc.
while (points = iterator.getNext()) {
    this.emit(points);
}
```

This would eliminate the ugliness of calling `read` once with empty state and then with a non-empty one.

As for `emit`, the problem with `to` and stopping the live iteration could be avoided by adding some other signaling path, e.g. adding `eof: true` to the result. While this would work, I’m actually starting to suspect that `emit` is just too different from the adapters. For adapters, one wants to implement live using *pull* while the natural thing for emit is *push*. Maybe it makes most sense to split the implementation so that:

  * `source` would contain the scheduler and a way to enqueue incoming points (that part coming later, for now it would just emit them)
  * `emit` would just push points to the enqueuing API at the right time, i.e. the implementation would not change much from today
  * `read` would additionally contain logic for pseudo-live, lagging, etc. and would call `read` on adapters

I won’t claim I thought through all the consequences though.

**Comment by demmer** [comment]
Regarding iterators I thought about that idea but it seemed like it would make the simple adapters that don't actually do paging overly complicated.

My high level idea was to actually use that kind of pattern inside the adapter -- i.e. a given adapter could actually return an iterator object as the state variable and then easily dispatch to its methods on subsequent calls to read.

As far as how to handle emit I feel like I came to the same conclusion -- it's just different enough that it doesn't make sense to couple them together.

I would like to move the tick generation logic into source but other than that I think we agree on the breakdown of responsibilities.

**Comment by bkutil** [comment]
> one of the real adapters (influx probably)

I'd like to take care of that, as soon as the approach is clear

**Comment by demmer** [comment]
Closing in favor of #248

**Pull request closed without merging**
