### PR TITLE
Uniq on nested fields

### PR DESCRIPTION
**Pull request by bkutil**
Add support for nested fields to `uniq` proc, by comparing values using `values.equal`.

refs: #55

### CODE REVIEW

**Comment by bkutil** [comment]
cc: @dmajda @demmer

**Comment by dmajda** [comment]
+1 with the guard added, the `cols`/`fields` thing is up to you

**Comment by bkutil** [comment]
@dmajda - added the guard, renamed `cols` to `fields`.

**Comment by dmajda** [comment]
+1

**Pull request merged**
