### PR TITLE
Purge utils.fromNative from views

### PR DESCRIPTION
**Pull request by dmajda**
Views should properly handle all Juttle data types by themselves, there is no need for the conversion.

### CODE REVIEW

**Comment by dmajda** [comment]
@bkutil

**Comment by bkutil** [comment]
It looks like `fromNative` is now dead code?

**Comment by dmajda** [comment]
No, it is still used in `TestView`. The biggest blocker of its removal is changing JuttleSpec output, which I just filed an issue for (#208).

**Comment by bkutil** [comment]
Cool, thanks :) +1 for this one.

**Pull request merged**
