### PR TITLE
README: update with external docs site links

### PR DESCRIPTION
**Pull request by demmer**
As suggested by @mccanne, change the paragraph in the readme
that talks about docs to have links to the external docs site and not
the source markdown files.

### CODE REVIEW

**Comment by demmer** [comment]
@dmehra @mccanne take a look and let me know what you think.

**Comment by mccanne** [comment]
+1

**Comment by dmehra** [comment]
While we're at it, how about a link to wiki as well?
```
For juttle project information, see our [wiki](https://github.com/juttle/juttle/wiki).
```

**Comment by dmehra** [comment]
Also, we have the Examples section, that could use the addition of this (just before Hello World):
```
For end-to-end examples of juttle usage, see [outrigger examples README](https://github.com/juttle/outrigger/tree/master/examples).
```

**Comment by dmehra** [comment]
+1 to your change @demmer and if you did the additional two as well, i think we'd be done with linking out of the README.

**Comment by demmer** [comment]
@dmehra I added additional links as you suggested.

**Pull request merged**
