### PR TITLE
Add documentation for nested fields

### PR DESCRIPTION
**Pull request by bkutil**
Fixes: #184

### CODE REVIEW

**Comment by bkutil** [comment]
cc: @dmehra

**Comment by dmajda** [comment]
Looks good beside the terminology thing. I think @dmehra should still have a look.

**Comment by bkutil** [comment]
Changed wording to 'fields with array/object values' or 'object/array fields', fixed spacing in example.

**Comment by dmehra** [comment]
lgtm but @demmer and i agreed on inlining code examples if they are wrapped in text that discusses them. With that logic, we should put code snippets decorated with ```juttle into fields.md. They will get syntax checked.

**Comment by bkutil** [comment]
@dmehra - I wasn't aware of that - I understood you aimed for having the examples in separate juttle files, so they are executable. Good to know - thanks.

**Pull request merged**
